from django.db import models

class VehicleMakes(models.TextChoices):
    # Common Makes
    ACURA = "Acura", "Acura"
    AUDI = "Audi", "Audi"
    BMW = "BMW", "BMW"
    CHEVROLET = "Chevrolet", "Chevrolet"
    CHRYSLER = "Chrysler", "Chrysler"
    DODGE = "Dodge", "Dodge"
    FIAT = "Fiat", "Fiat"
    FORD = "Ford", "Ford"
    GMC = "GMC", "GMC"
    GENESIS = "Genesis", "Genesis"
    HONDA = "Honda", "Honda"
    HYUNDAI = "Hyundai", "Hyundai"
    INFINITI = "Infiniti", "Infiniti"
    JAGUAR = "Jaguar", "Jaguar"
    JEEP = "Jeep", "Jeep"
    KIA = "Kia", "Kia"
    LAND_ROVER = "Land Rover", "Land Rover"
    LEXUS = "Lexus", "Lexus"
    LINCOLN = "Lincoln", "Lincoln"
    MAZDA = "Mazda", "Mazda"
    MERCEDES_BENZ = "Mercedes-Benz", "Mercedes-Benz"
    MITSUBISHI = "Mitsubishi", "Mitsubishi"
    NISSAN = "Nissan", "Nissan"
    PORSCHE = "Porsche", "Porsche"
    RAM = "Ram", "Ram"
    SUBARU = "Subaru", "Subaru"
    TESLA = "Tesla", "Tesla"
    TOYOTA = "Toyota", "Toyota"
    VOLKSWAGEN = "Volkswagen", "Volkswagen"
    VOLVO = "Volvo", "Volvo"
