# Generated by Django 5.2.1 on 2025-12-18 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('license_plate', models.CharField(blank=True, max_length=10)),
                ('registration', models.FileField(blank=True, null=True, upload_to='vehicle/registration/')),
                ('insurance', models.FileField(blank=True, null=True, upload_to='vehicle/insurance/')),
                ('service_records', models.FileField(blank=True, null=True, upload_to='vehicle/service/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle/images/')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='house.purchaselocation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
