# Generated by Django 5.2.1 on 2025-06-23 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='circuit_diagrams/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricalPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(blank=True, max_length=25)),
                ('description', models.TextField(blank=True)),
                ('breaker_type', models.CharField(blank=True, max_length=25)),
                ('kind', models.CharField(choices=[('Main Panel', 'Main Panel'), ('Subpanel', 'Subpanel'), ('Disconnect', 'Disconnect')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location_description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('suv', 'SUV'), ('motorcycle', 'Motorcycle'), ('boat', 'Boat'), ('rv', 'RV'), ('other', 'Other')], default='car', max_length=15)),
                ('oil_type', models.CharField(blank=True, max_length=100)),
                ('oil_capacity', models.CharField(blank=True, max_length=50)),
                ('oil_filter_part_number', models.CharField(blank=True, max_length=100)),
                ('air_filter_part_number', models.CharField(blank=True, max_length=100)),
                ('last_oil_change_date', models.DateField(blank=True, null=True)),
                ('last_oil_change_mileage', models.IntegerField(blank=True, null=True)),
                ('current_mileage', models.IntegerField(blank=True, null=True)),
                ('registration', models.FileField(blank=True, upload_to='vehicle_docs/registration/')),
                ('insurance', models.FileField(blank=True, upload_to='vehicle_docs/insurance/')),
                ('owners_manual', models.FileField(blank=True, upload_to='vehicle_docs/manuals/')),
                ('service_records', models.FileField(blank=True, upload_to='vehicle_docs/service/')),
                ('image', models.ImageField(blank=True, upload_to='vehicle_images/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['year', 'make', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_number', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('breaker_size', models.CharField(choices=[('15A', '15A'), ('20A', '20A'), ('30A', '30A'), ('40A', '40A'), ('50A', '50A'), ('60A', '60A')], max_length=10)),
                ('pole_type', models.CharField(choices=[('single', 'Single Pole'), ('double', 'Double Pole')], max_length=10)),
                ('voltage', models.CharField(choices=[('120V', '120V'), ('240V', '240V')], max_length=10)),
                ('protection_type', models.CharField(choices=[('none', 'No Protection'), ('gfci', 'GFCI (Ground Fault Circuit Interrupter)'), ('afci', 'AFCI (Arc Fault Circuit Interrupter)'), ('dual_function', 'Dual Function (AFCI + GFCI)')], default='none', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagrams', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuits', to='house.circuitdiagram')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuits', to='house.electricalpanel')),
                ('rooms', models.ManyToManyField(related_name='circuits', to='house.room')),
            ],
            options={
                'ordering': ['circuit_number'],
                'unique_together': {('circuit_number',)},
            },
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('appliance_type', models.CharField(choices=[('gas', 'Gas'), ('electric', 'Electric'), ('induction', 'Induction'), ('other', 'Other')], default='other', max_length=10)),
                ('warranty_alert_dismissed', models.BooleanField(default=False)),
                ('warranty_alert_dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('owners_manual', models.FileField(blank=True, null=True, upload_to='owners_manuals/')),
                ('specs', models.FileField(blank=True, null=True, upload_to='specs/')),
                ('install_docs', models.FileField(blank=True, null=True, upload_to='install_docs/')),
                ('service_manual', models.FileField(blank=True, null=True, upload_to='service_manual/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='appliance_images/')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('registered', models.BooleanField(default=False)),
                ('warranty_expires', models.DateField(blank=True, null=True)),
                ('power_demands', models.CharField(blank=True, choices=[('15A', '15A'), ('20A', '20A'), ('30A', '30A'), ('40A', '40A'), ('50A', '50A'), ('60A', '60A')], max_length=5, null=True)),
                ('pole_type', models.CharField(blank=True, choices=[('single', 'Single Pole'), ('double', 'Double Pole')], max_length=10, null=True)),
                ('voltage', models.CharField(blank=True, choices=[('120V', '120V'), ('240V', '240V')], max_length=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appliances', to='house.purchaselocation')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='house.room')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaintColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paint_code', models.CharField(max_length=100)),
                ('paint_color', models.CharField(max_length=100)),
                ('paint_brand', models.CharField(blank=True, max_length=100)),
                ('paint_base', models.CharField(blank=True, max_length=100)),
                ('finish_type', models.CharField(blank=True, choices=[('Flat', 'Flat'), ('Matte', 'Matte'), ('Satin', 'Satin'), ('Eggshell', 'Eggshell'), ('Semigloss', 'Semigloss'), ('Gloss', 'Gloss')], max_length=20, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paint_colors', to='house.purchaselocation')),
                ('rooms', models.ManyToManyField(related_name='paint_colors', to='house.room')),
            ],
            options={
                'ordering': ['paint_color'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('Receptacle', 'Receptacle'), ('Switch', 'Switch'), ('Light', 'Light'), ('Detector', 'Detector'), ('Ceiling Fan', 'Ceiling Fan'), ('Floor Heating', 'Floor Heating')], max_length=50)),
                ('location_description', models.TextField(blank=True)),
                ('position_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protection_type', models.CharField(choices=[('none', 'No Protection'), ('gfci', 'GFCI (Ground Fault Circuit Interrupter)'), ('afci', 'AFCI (Arc Fault Circuit Interrupter)'), ('dual_function', 'Dual Function (AFCI + GFCI)')], default='none', max_length=15)),
                ('attached_appliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='house.appliance')),
                ('circuit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='house.circuit')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='house.room')),
            ],
            options={
                'ordering': ['room__name', 'device_type'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_rotation', 'Tire Rotation'), ('brake_service', 'Brake Service'), ('transmission', 'Transmission Service'), ('coolant', 'Coolant Service'), ('air_filter', 'Air Filter'), ('fuel_filter', 'Fuel Filter'), ('spark_plugs', 'Spark Plugs'), ('inspection', 'Inspection'), ('other', 'Other')], max_length=20)),
                ('date_performed', models.DateField()),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('receipt', models.FileField(blank=True, upload_to='maintenance_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='house.vehicle')),
            ],
            options={
                'ordering': ['-date_performed'],
            },
        ),
        migrations.CreateModel(
            name='TorqueSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=100)),
                ('torque_value', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torque_settings', to='house.vehicle')),
            ],
            options={
                'ordering': ['component'],
                'unique_together': {('vehicle', 'component')},
            },
        ),
    ]
