# Generated by Django 5.2.1 on 2025-05-23 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='circuit_diagrams/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaintColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paint_code', models.CharField(max_length=100)),
                ('paint_color', models.CharField(max_length=100)),
                ('paint_brand', models.CharField(blank=True, max_length=100)),
                ('paint_base', models.CharField(blank=True, max_length=100)),
                ('finish_type', models.CharField(blank=True, max_length=50)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rooms', models.ManyToManyField(related_name='paint_colors', to='tracker.room')),
            ],
            options={
                'ordering': ['paint_color'],
            },
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('appliance_type', models.CharField(choices=[('gas', 'Gas'), ('electric', 'Electric'), ('induction', 'Induction'), ('other', 'Other')], default='other', max_length=10)),
                ('receipt', models.FileField(blank=True, upload_to='receipts/')),
                ('owners_manual', models.FileField(blank=True, upload_to='owners_manuals/')),
                ('specs', models.FileField(blank=True, upload_to='specs/')),
                ('install_docs', models.FileField(blank=True, upload_to='install_docs/')),
                ('image', models.ImageField(blank=True, upload_to='appliance_images/')),
                ('purchase_location', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('registered', models.BooleanField(default=False)),
                ('warranty_expires', models.DateField(blank=True, null=True)),
                ('power_demands', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.room')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_number', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('breaker_size', models.CharField(choices=[('15A', '15A'), ('20A', '20A'), ('30A', '30A'), ('40A', '40A'), ('50A', '50A'), ('60A', '60A')], max_length=10)),
                ('gfci', models.BooleanField(default=False, verbose_name='GFCI Protected')),
                ('afci', models.BooleanField(default=False, verbose_name='AFCI Protected')),
                ('cafi', models.BooleanField(default=False, verbose_name='CAFI Protected')),
                ('pole_type', models.CharField(choices=[('single', 'Single Pole'), ('double', 'Double Pole')], max_length=10)),
                ('voltage', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagrams', models.ManyToManyField(blank=True, related_name='circuits', to='tracker.circuitdiagram')),
                ('rooms', models.ManyToManyField(blank=True, related_name='circuits', to='tracker.room')),
            ],
            options={
                'ordering': ['circuit_number'],
                'unique_together': {('circuit_number',)},
            },
        ),
    ]
