# Generated by Django 5.2.1 on 2025-05-23 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='appliance',
            name='power_demands',
            field=models.CharField(choices=[('15A', '15A'), ('20A', '20A'), ('30A', '30A'), ('40A', '40A'), ('50A', '50A'), ('60A', '60A')], max_length=100),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='purchase_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appliances', to='tracker.purchaselocation'),
        ),
    ]
