# Generated by Django 5.2.1 on 2025-05-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_purchaselocation_alter_appliance_power_demands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='power_demands',
            field=models.CharField(choices=[('15A', '15A'), ('20A', '20A'), ('30A', '30A'), ('40A', '40A'), ('50A', '50A'), ('60A', '60A')], max_length=5),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='voltage',
            field=models.CharField(blank=True, choices=[('120V', '120V'), ('240V', '240V')], max_length=10),
        ),
    ]
