# Generated by Django 5.2.1 on 2025-05-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_appliance_power_demands_alter_circuit_voltage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='pole_type',
            field=models.CharField(choices=[('single', 'Single Pole'), ('double', 'Double Pole')], default='SINGLE', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliance',
            name='voltage',
            field=models.CharField(blank=True, choices=[('120V', '120V'), ('240V', '240V')], max_length=10),
        ),
    ]
