# Generated by Django 5.2.1 on 2025-05-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_appliance_pole_type_appliance_voltage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='pole_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Pole'), ('double', 'Double Pole')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='voltage',
            field=models.CharField(blank=True, choices=[('120V', '120V'), ('240V', '240V')], max_length=10, null=True),
        ),
    ]
