# Generated by Django 5.2.1 on 2025-05-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_appliance_pole_type_alter_appliance_voltage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='power_demands',
            field=models.CharField(blank=True, choices=[('15A', '15A'), ('20A', '20A'), ('30A', '30A'), ('40A', '40A'), ('50A', '50A'), ('60A', '60A')], max_length=5, null=True),
        ),
    ]
