# Generated by Django 5.2.1 on 2025-05-29 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_appliance_power_demands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintcolor',
            name='purchase_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paint_colors', to='tracker.purchaselocation'),
        ),
    ]
