# Generated by Django 5.2.1 on 2025-05-30 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_rename_notes_outlet_location_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outlet',
            options={'ordering': ['room__name', 'device_type']},
        ),
        migrations.AddField(
            model_name='outlet',
            name='circuit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='tracker.circuit'),
            preserve_default=False,
        ),
    ]
