# Generated by Django 5.2.1 on 2025-05-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_outlet_options_outlet_circuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='rooms',
            field=models.ManyToManyField(related_name='circuits', to='tracker.room'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='voltage',
            field=models.CharField(choices=[('120V', '120V'), ('240V', '240V')], max_length=10),
        ),
    ]
