# Generated by Django 5.2.1 on 2025-06-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_circuit_rooms_alter_circuit_voltage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='location_description',
            field=models.TextField(default='NW corner', max_length=500),
            preserve_default=False,
        ),
    ]
