# Generated by Django 5.2.1 on 2025-06-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_room_location_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='appliance_images/'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='install_docs',
            field=models.FileField(blank=True, null=True, upload_to='install_docs/'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='owners_manual',
            field=models.FileField(blank=True, null=True, upload_to='owners_manuals/'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='specs',
            field=models.FileField(blank=True, null=True, upload_to='specs/'),
        ),
        migrations.AlterField(
            model_name='paintcolor',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='location_description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
