# Generated by Django 5.2.1 on 2025-06-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_appliance_image_alter_appliance_install_docs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintcolor',
            name='finish_type',
            field=models.CharField(blank=True, choices=[('FLAT', 'Flat'), ('MATTE', 'Matte'), ('SATIN', 'Satin'), ('EGGSHELL', 'Eggshell'), ('SEMIGLOSS', 'Semigloss'), ('GLOSS', 'Gloss')], max_length=20, null=True),
        ),
    ]
