# Generated by Django 5.2.1 on 2025-06-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_alter_paintcolor_finish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
