# Generated by Django 5.2.1 on 2025-06-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_appliance_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='service_manual',
            field=models.FileField(blank=True, null=True, upload_to='service_manual/'),
        ),
    ]
