# Generated by Django 5.2.1 on 2025-06-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_appliance_service_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintcolor',
            name='finish_type',
            field=models.CharField(blank=True, choices=[('Flat', 'Flat'), ('Matte', 'Matte'), ('Satin', 'Satin'), ('Eggshell', 'Eggshell'), ('Semigloss', 'Semigloss'), ('Gloss', 'Gloss')], max_length=20, null=True),
        ),
    ]
