# Generated by Django 5.2.1 on 2025-06-02 15:30

import django.db.models.deletion
from django.db import migrations, models


def create_default_panel_and_assign_circuits(apps, schema_editor):
    ElectricPanel = apps.get_model('tracker', 'ElectricPanel')
    Circuit = apps.get_model('tracker', 'Circuit')

    # Only create default panel if there are existing circuits
    if Circuit.objects.exists():
        default_panel = ElectricPanel.objects.create(
            kind="Main Panel",
            brand="Unknown",
            model="",
            description="Default Main Panel",
            breaker_type=""
        )

        # Assign all existing circuits to this panel
        Circuit.objects.all().update(panel=default_panel)


def reverse_default_panel_assignment(apps, schema_editor):
    Circuit = apps.get_model('tracker', 'Circuit')
    Circuit.objects.all().update(panel=None)


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0017_alter_paintcolor_finish_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectricPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=25)),
                ("model", models.CharField(blank=True, max_length=25)),
                ("description", models.TextField(blank=True)),
                ("breaker_type", models.CharField(blank=True, max_length=25)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("Main Panel", "Main Panel"),
                            ("Subpanel", "Subpanel"),
                            ("Disconnect", "Disconnect"),
                        ],
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),

        migrations.AddField(
            model_name="circuit",
            name="panel",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circuits",
                to="tracker.electricpanel",
            ),
        ),

        migrations.RunPython(
            create_default_panel_and_assign_circuits,
            reverse_default_panel_assignment
        ),

        migrations.AlterField(
            model_name="circuit",
            name="panel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circuits",
                to="tracker.electricpanel",
            ),
        ),
    ]
