# Generated by Django 5.2.1 on 2025-06-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_create_electric_panel'),
    ]

    operations = [
    ]
