# Generated by Django 5.2.1 on 2025-06-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_auto_20250602_1857'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElectricPanel',
            new_name='ElectricalPanel',
        ),
    ]
