# Generated by Django 5.2.1 on 2025-06-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_rename_electricpanel_electricalpanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='warranty_alert_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appliance',
            name='warranty_alert_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
