# Generated by Django 5.2.1 on 2025-06-03 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_appliance_warranty_alert_dismissed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='position_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='circuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='tracker.circuit'),
        ),
    ]
