# Generated by Django 5.2.1 on 2025-06-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_outlet_position_number_alter_outlet_circuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='afci',
            field=models.BooleanField(blank=True, help_text='Leave blank to inherit from circuit', null=True, verbose_name='AFCI Protected'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='cafi',
            field=models.BooleanField(blank=True, help_text='Leave blank to inherit from circuit', null=True, verbose_name='CAFI Protected'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='gfci',
            field=models.BooleanField(blank=True, help_text='Leave blank to inherit from circuit', null=True, verbose_name='GFCI Protected'),
        ),
    ]
