# Generated by Django 5.2.1 on 2025-06-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_outlet_afci_outlet_cafi_outlet_gfci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='afci',
            field=models.BooleanField(default=False, verbose_name='AFCI Protected'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='cafi',
            field=models.BooleanField(default=False, verbose_name='CAFI Protected'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='gfci',
            field=models.BooleanField(default=False, verbose_name='GFCI Protected'),
        ),
    ]
