# Generated by Django 5.2.1 on 2025-06-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_alter_outlet_afci_alter_outlet_cafi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='afci',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='cafi',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='gfci',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='afci',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='cafi',
        ),
        migrations.RemoveField(
            model_name='outlet',
            name='gfci',
        ),
        migrations.AddField(
            model_name='circuit',
            name='protection_type',
            field=models.CharField(choices=[('none', 'No Protection'), ('gfci', 'GFCI (Ground Fault Circuit Interrupter)'), ('afci', 'AFCI (Arc Fault Circuit Interrupter)'), ('dual_function', 'Dual Function (AFCI + GFCI)')], default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='outlet',
            name='protection_type',
            field=models.CharField(choices=[('none', 'No Protection'), ('gfci', 'GFCI (Ground Fault Circuit Interrupter)'), ('afci', 'AFCI (Arc Fault Circuit Interrupter)'), ('dual_function', 'Dual Function (AFCI + GFCI)')], default='none', max_length=15),
        ),
    ]
