# Generated by Django 5.2.1 on 2025-06-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_remove_circuit_afci_remove_circuit_cafi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='device_type',
            field=models.CharField(choices=[('Receptacle', 'Receptacle'), ('Switch', 'Switch'), ('Light', 'Light')], max_length=50),
        ),
    ]
