# Generated by Django 5.2.1 on 2025-06-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_alter_outlet_device_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Outlet',
            new_name='Device',
        ),
    ]
