# Generated by Django 5.2.1 on 2025-06-05 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_rename_outlet_to_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='circuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='tracker.circuit'),
        ),
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='tracker.room'),
        ),
    ]
