# Generated by Django 5.2.1 on 2025-06-05 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_rename_outlet_to_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='attached_appliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='tracker.appliance'),
        ),
    ]
